# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Site + Docs

on:
  push:
    branches: [ "site-sm-pages" ]
  pull_request:
    branches: [ "site-sm-pages" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Amalgamate site and docs
      run: |
        # creds
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git fetch

        # get the site and the docs
        git checkout origin/site-sm -- site
        git checkout origin/main -- docs

        # move site to the root and remove the folder
        mv site/* .
        rm -r site

        # rename docs
        mv docs documentation

        # Commit changes
        git add .
        git diff-index --quiet HEAD ||  git commit -am "Build latest docs sites"
        git push -f
