# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "site" ]
  pull_request:
    branches: [ "site" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Build Site
      env:
        SITE_PATH: 'site'
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git fetch

        # Build site into 'site/'
        rm -rf $SITE_PATH
        mkdir -p $SITE_PATH
        npm install
        npm run build

        # Commit changes
        git add .
        git diff-index --quiet HEAD ||  git commit -am "Build site"
        git push -f